# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6b46edf909b1f610b5a4810208f392ced0ba81da48ae6d80b4426b3aeb8bdb80e99aa484ca9a7d4b172da02beed40ad0fcbc8c2d120ed64cf5c1946feeae1ffd

test:
  secret_key_base: 85a94e733be7da3c3b153a9a46095553948d28cfe77729cb1210b0c8973bb59eca01e5650bfc3acc59562a71d5b04c2db217bb110276baf8fe1a491eb963a866

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
